name: "Build Ultrahand"

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Build-Ultrahand:
    name: "Release"
    runs-on: "ubuntu-latest"
    container: "ghcr.io/irneracoonovich/devkita64:latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup environment
        run: |
          sudo apt-get update || true
          sudo apt-get install -y unzip zip curl
          export DEVKITPRO=/opt/devkitpro
          export DEVKITA64=/opt/devkitpro/devkitA64

      - name: Get version
        run: |
          RAW_VERSION=$(awk '/^APP_VERSION[[:space:]]*:=/ {gsub(/^APP_VERSION[[:space:]]*:=/, ""); gsub(/[[:space:]]+$/, ""); print $0}' Makefile 2>/dev/null | tr -d '\r' || echo "unknown")
          RAW_VERSION=$(echo "$RAW_VERSION" | tr -d ' ')
          echo "VERSION=$RAW_VERSION" >> $GITHUB_ENV
          echo "TAG=v${RAW_VERSION:-$(git rev-parse --short HEAD)}" >> $GITHUB_ENV

      - name: Build ovlmenu.ovl
        run: make V=1

      - name: Download latest sdout.zip
        run: |
          curl -sL "https://api.github.com/repos/ppkantorski/Ultrahand-Overlay/releases/latest" -o latest.json
          DOWNLOAD_URL=$(grep -oP '"browser_download_url": "\Khttps://[^"]*sdout\.zip"' latest.json | sed 's/"//g')
          [ -n "$DOWNLOAD_URL" ] || { echo "未找到sdout.zip"; exit 1; }
          curl -sL "$DOWNLOAD_URL" -o sdout.zip

      - name: Replace ovlmenu.ovl in sdout.zip
        run: |
          mkdir -p workdir && cd workdir
          unzip -q ../sdout.zip
          mkdir -p switch/.overlays/
          cp ../ovlmenu.ovl switch/.overlays/
          zip -r ../sdout-modified.zip ./*
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # prerelease: ${{ contains(env.VERSION, 'pre-release') }}
          files: ovlmenu.ovl,sdout-modified.zip
          tag_name: ${{ env.TAG }}
          name: "Ultrahand ${{ env.VERSION }}"
          body: "包含最新构建“国行版自动转国际版”的 ovlmenu.ovl 和替换后的 sdout.zip"
          generate_release_notes: true
